default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  password: postgres
  pool: 10

development:
  <<: *default
  database: shop

test:
  <<: *default
  database: shop_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>